### PR TITLE
1.10.0-beta2 release notes [WIP]

### PR DESCRIPTION
**Pull request by sascala**
## Description
Release notes for beta2

## Urgency
- [X] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-website#testing-your-updates-locally) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-website#contribution-workflow).

### CODE REVIEW

File: src/releases/1.10-beta2/notes.md [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+
+- The "Deployments" subpage under the "Services" tab has been moved to a toggle-able modal in the "Services" page.
+- The "Security" tab has been removed. The "Secrets" tab that used to be under "Security" is now a top-level tab.
+- The "Universe" tab has been renamed to "Catalog" and the "Installed" subpage has been removed.
+- The "System Overview" tab has been renamed to "Overview".
+
+## Updated DC/OS Data Services
+
+- Rolling Configuration Update and Upgrades support via CLI.
+- Ability to deploy Data Services into Folders to enable multi team deployments.
```
Comment (judithpatudith) [inline src/releases/1.10-beta2/notes.md]: This might be EE?

File: src/releases/1.10-beta2/notes.md [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+- DCOS-15590 - DCOS cli confirm() is not non-interactive safe.
+- DCOS-15937 - Pods do not receive SIGTERM.
+- DCOS-16151 - Marathon Endpoints are not responding.
+- DCOS-16547 - Task state does not update after the agent running it was removed from the cluster.
+- DCOS-16564 - UI error message references Marathon command.
+- DCOS-17294 - Unable to curl (resolve) applications using Mesos DNS names.
+- DCOS-17502 - AdminRouter rejecting request to install package.
+- DCOS_OSS-1340 - Spartan "autoip" DNS should resolve to host IP for UCR in bridge network.
+- DCOS_OSS-1486 - Metrics agent crashes when the mesos containers endpoint is missing fields.
+- INFINITY-1143 - Update / Uninstall. DSE does not support rolling upgrade.
```
Comment (judithpatudith) [inline src/releases/1.10-beta2/notes.md]: Data services upgrades may be enterprise only?

File: src/releases/1.10-beta2/index.jade [hunk 3]
```diff
@@ -0,0 +1,25 @@
+extends ../../../layouts/base-whitefooter.jade
+
+
+block head
+  title DC/OS 1.10.0 Beta 2
```
Comment (judithpatudith) [inline src/releases/1.10-beta2/index.jade]: Should be consistent if naming is 1.10.0 Beta 2 or 1.10-beta2
- is there a space between beta2?
- do we include the .0? 
- hyphen? 
- capitalization?

File: src/releases/1.10-beta2/notes.md [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+  You can now configure Spartan to delegate a particular domain (e.g. "\*.foo.company.com") to a particular upstream. <!-- I could use more information here -->
+
+- Increased CNI network support.
+  DC/OS now supports any type of CNI network. [View the documentation](/docs/1.10/networking/virtual-networks/cni-plugins/).
+
+## Platform
+- Node and Cluster health checks.
+  Write your own custom health checks or use the predefined checks to access and use information about your cluster, including available ports, Mesos agent status, and IP detect script validation. [View the documentation](/docs/1.10/installing/custom/node-cluster-health-check/).
+- Enhanced upgrades with pre/post flight checks.
+- UCR.
```
Comment (sascala) [inline src/releases/1.10-beta2/notes.md]: I have a little inline comment about that -- I'm working on that.

File: src/releases/1.10-beta2/notes.md [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+- Scale and performance limits.
+
+## CLI
+- Multi-cluster support. [View the documentation](/docs/1.10/cli/multi-cluster-cli/).
+
+## GUI
+The GUI sidebar tabs have been updated to offer a more intuitive experience.
+
+- The "Deployments" subpage under the "Services" tab has been moved to a toggle-able modal in the "Services" page.
+- The "Security" tab has been removed. The "Secrets" tab that used to be under "Security" is now a top-level tab.
```
Comment (sascala) [inline src/releases/1.10-beta2/notes.md]: good catch

File: src/releases/1.10-beta2/notes.md (hunk 2 above)
Comment (sascala) [inline src/releases/1.10-beta2/notes.md]: Well, they appear in the OSS universe.

File: src/releases/1.10-beta2/notes.md [hunk 6]
```diff
@@ -0,0 +1,163 @@
...
+- Ability to deploy Data Services into Folders to enable multi team deployments.
+- Ability to deploy to CNI-Based Virtual Networks.
+
+The following updated data services packages are also in beta and are compatible with DC/OS 1.10.
+
+- Beta Cassandra. [Documentation](https://docs.mesosphere.com/service-docs/beta-cassandra/v1.0.31-3.0.13-beta/). [Release Notes](https://github.com/mesosphere/dcos-commons/releases/tag/cassandra-1.0.31-3.0.13-beta).
+
+- Beta Elastic. [Documentation](https://docs.mesosphere.com/service-docs/beta-elastic/v1.0.15-5.5.1-beta/). [Release Notes](https://github.com/mesosphere/dcos-commons/releases/tag/elastic-1.0.15-5.5.1-beta).
+
+- Beta HDFS. [Documentation](https://docs.mesosphere.com/service-docs/beta-hdfs/v1.3.3-2.6.0-cdh5.11.0-beta/). [Release Notes](https://github.com/mesosphere/dcos-commons/releases/tag/hdfs-1.3.3-2.6.0-cdh5.9.1-beta).
```
Comment (sascala) [inline src/releases/1.10-beta2/notes.md]: 👍

File: src/releases/1.10-beta2/notes.md [hunk 7]
```diff
@@ -0,0 +1,163 @@
...
+- DCOS-16144 - DC/OS CLI: AttributeError: 'str' object has no attribute 'status_code'.
+- DCOS-16528 - Incorrect command in Edit Service modal.
+- DCOS-16643 - dcos tunnel doesn't work with DC/OS CLI 0.5.x.
+- DCOS-16658 - Move "Secrets" back to "Resources" menu section.
+- DCOS-17219 - Marathon-LB broken in DC/OS 1.10.
+- DCOS-17284 - [1.10] GUI bug: container type must be defined.
+- DCOS-17321 - Fix upgrade of Marathon-lb from 1.9-1.10.
+- DCOS-17412 - bouncer: aces must be unique for [user,resource] and [group,resource].
+- DCOS-17430 - bouncer: policyquery is slow against cockroachdb.
+- DCOS-17473 - bouncer: stay close to official transaction retry logic.
```
Comment (sascala) [inline src/releases/1.10-beta2/notes.md]: Not sure. @somikbehera ?

File: src/releases/1.10-beta2/notes.md [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+DC/OS 1.10 includes many new capabilities for Operators and expands the collection of Data & Developer Services with a focus on:
+- Core DC/OS Service Continuity - System resilience, cluster and node checks, UCR and Pods improvements.
+- CNI Networking enhancements for broader networking support.
+- Data Services enhancements.
+
+### Contents
+- [New Features and Capabilities](#new-features)
+- [Breaking Changes](#breaking-changes)
+- [Known Issues and Limitations](#known-issues)
+- [Issues Fixed since 1.9.0](#fixed-issues)
```
Comment (sascala) [inline src/releases/1.10-beta2/notes.md]: 👍

File: src/releases/1.10-beta2/notes.md (hunk 1 above)
Comment (sascala) [inline src/releases/1.10-beta2/notes.md]: I'm told no.

File: src/releases/1.10-beta2/notes.md [hunk 9]
```diff
@@ -0,0 +1,158 @@
...
+- DCOS-16144 - DC/OS CLI: AttributeError: 'str' object has no attribute 'status_code'.
+- DCOS-16528 - Incorrect command in Edit Service modal.
+- DCOS-17219 - Marathon-LB broken in DC/OS 1.10.
+- DCOS-17284 - [1.10] GUI bug: container type must be defined.
+- DCOS-17321 - Fix upgrade of Marathon-lb from 1.9-1.10.
+- DCOS-17412 - bouncer: aces must be unique for [user,resource] and [group,resource].
+- DCOS-17430 - bouncer: policyquery is slow against cockroachdb.
+- DCOS-17473 - bouncer: stay close to official transaction retry logic.
+- DCOS-17502 - Marathon cannot retrieve JSON web key set: 'the trustAnchors parameter must be non-empty'.
+- DCOS-17511 - cockroachdb: upgrade to v1.0.4.
```
Comment (judithpatudith) [inline src/releases/1.10-beta2/notes.md]: I think this is EE only? (open uses ZooKeeper instead)
